# Generated by Django 3.2.5 on 2021-09-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='jimam', max_length=90),
            preserve_default=False,
        ),
    ]
