# Generated by Django 3.2.5 on 2021-09-22 05:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210922_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=account.models.Token.get_random_alphanumeric_string, max_length=100, verbose_name='Token'),
        ),
    ]
