# Generated by Django 3.2.5 on 2021-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('live_quotes', models.BooleanField(null=True)),
                ('update_every', models.IntegerField(default=5, null=True)),
                ('default_commission', models.FloatField(default=0, null=True)),
                ('include_cash_balance', models.BooleanField(null=True)),
                ('update_cash_balance_with_transaction', models.BooleanField(null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
