# Generated by Django 3.2.5 on 2021-07-09 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('live_quotes', models.BooleanField(default=True)),
                ('update_every', models.IntegerField(default=5, null=True)),
                ('default_commission', models.FloatField(blank=True, default=0, null=True)),
                ('cash', models.FloatField(blank=True, default=1000, null=True)),
                ('include_cash_balance', models.BooleanField(default=True)),
                ('update_cash_balance_with_transaction', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('purchase_date', models.DateField(auto_now_add=True, null=True)),
                ('commissions', models.FloatField(default=0, null=True)),
                ('fees', models.FloatField(default=0, null=True)),
                ('update_cash_balance', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True)),
                ('quantity', models.IntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('quantity', models.PositiveBigIntegerField(default=0, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('modified', models.DateField(auto_now_add=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='dashboard.portfolio')),
            ],
        ),
    ]
