# Generated by Django 3.2.5 on 2021-07-04 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210704_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='default_commission',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='update_every',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
