# Generated by Django 3.2.5 on 2021-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210903_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestate',
            name='columnsdata',
            field=models.TextField(max_length=5000, null=True, verbose_name='ColumnsData'),
        ),
    ]
