# Generated by Django 3.2.5 on 2021-07-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210704_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='modified',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
