# Generated by Django 3.2.5 on 2021-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_tablestate_columnsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablestate',
            name='columnsdata',
        ),
        migrations.AddField(
            model_name='tablestate',
            name='data',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tablestate',
            name='tablename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TableName'),
        ),
    ]
