# Generated by Django 3.2.5 on 2021-07-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210704_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='include_cash_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='live_quotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='update_cash_balance_with_transaction',
            field=models.BooleanField(default=True),
        ),
    ]
