# Generated by Django 3.2.5 on 2021-09-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210909_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablestate',
            name='data',
        ),
        migrations.AddField(
            model_name='tablestate',
            name='statedata',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Data'),
        ),
    ]
