# Generated by Django 3.2.5 on 2021-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_tablestate_statedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestate',
            name='statedata',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Data'),
        ),
    ]
